### PR TITLE
Add client version to `DBBenchmark` object

### PR DESCRIPTION
**Pull request by Digitalfear117**
yeah

### CODE REVIEW

**Comment by iSlodinxOsu** [comment]
bro change the title lol

**Comment by Digitalfear117** [comment]
> bro change the title lol

It’s better this way :D

**Comment by iSlodinxOsu** [comment]
> > bro change the title lol
> 
> It’s better this way :D

i mean... i agree but you will see Levi is gonna change it :P

**Comment by Lekuruu** [comment]
> > > bro change the title lol
> > 
> > 
> > It’s better this way :D
> 
> i mean... i agree but you will see Levi is gonna change it :P

Yes, I will

**Review by Lekuruu — APPROVED** [review]

**Pull request merged**
